[package]
name = "staticsync"
version = "0.2.2"
authors = ["Marcus Correia <marknokalt@live.com>"]

[[bin]]
path = "src/main.rs"
name = "staticsync"

[dependencies]
dirs = "1.0"
filetime = "0.2"
getopts = "0.2"
rust-crypto = "0.2"
serde_json = "1.0"
