[package]
name = "staticsync"
version = "0.2.0"
authors = ["Marcus Correia <marknokalt@live.com>"]

[dependencies]
dirs = "1.0"
filetime = "0.2"
getopts = "0.2"
rust-crypto = "0.2"
serde_json = "1.0"
